### ISSUE TITLE
Accessibility updates

### ISSUE THREAD

**Issue by abbycabs** [github/maintainermonth#64]
Look into making the following updates on the website

```[tasklist]

### Tasks
- [ ] alt-text on images is missing
- [ ] text overlaps images
- [ ] fix tab order (current goes from menu on the side to the bottom of the site instead of main content)
- [ ] animations during scrolling is an anti-pattern for accessibility
```
  ![Screenshot 2023-03-10 130608](https://user-images.githubusercontent.com/617994/224716073-f51bcb36-fb13-4ce1-9564-0030b7f877cf.png)

**Comment by david-mbugua** [comment]
Hello, in regards to the first task, which images exactly lack alt-text? I would like to contribute to that.
Thanks.

**Comment by abbycabs** [comment]
Thanks @david-mbugua! I don't see any alt text present, so as much as you can add would be great.

The graphics are by [Ariel Davis](https://arielrdavis.com/), it would be nice to credit her in the alt text.
Thanks!

**Comment by abbycabs** [comment]
@david-mbugua opened a separate issue for the alt-text, please comment there so I can assign you

**Comment by pboling** [comment]
@abbycabs Does GitHub care about accessibility, or is this performative?

If GitHub does care, then perhaps someday this and inaccessible, anti-disabled, and racist, feature will finally be removed?  I hope it lands on someone's radar who is powerful enough to change things, and has a lot of time to read one of the longest discussion on this platform.

https://github.com/orgs/community/discussions/16925

**Comment by ashleywolf** [comment]
Substantially addressed in #380 — skip-to-content link added, `<main id="main-content" tabIndex="-1">` fixes tab order, `<nav aria-label="Main navigation">` and `<footer role="contentinfo">` improve screen reader navigation, decorative elements get `aria-hidden`, `focus-visible` outlines added, and heading hierarchy corrected (h2 -> h3). Thanks for the original audit, @abbycabs and @juliaferraioli!
