### ISSUE TITLE
Several UI/UX Issues

### ISSUE THREAD

**Issue by prathamshroff** [github/maintainermonth#87]
```[tasklist]
### Tasks
- [ ] Fix Text Overlaps in Event Descriptions
- [ ] Fix Text Overlap due to NavBar Heading (Maintainer Month) not being frozen
- [ ] Fix Text that's cut in half by some containers
- [ ] Add Responsive Layout so that Complete Event Info can be seen (look at screenshot's left side)
- [ ] Make Width of all Event Containers in Schedule equal for Large Screens (for > 3 Events/Row)
```

**Comment by prathamshroff** [comment]
Hi, I love what you're building here for the open-source community & just wanted to find my own way to contribute. These are some of the things that should be fixed in the front-end. In the process of learning myself, I'd be happy to try and fix some of these issues as well. Thanks.

**Comment by abbycabs** [comment]
Hi @prathamshroff feel free to send a PR!

**Comment by prathamshroff** [comment]
Would you be open to me fixing one task/error at a time? You'll have smaller more understandable PRs and it'll be easier for me.

**Comment by abbycabs** [comment]
Yes smaller PRs are best practice

**Comment by ashleywolf** [comment]
Addressed in #380 — event cards now use `min-width: 0; box-sizing: border-box` (fixes text cut-off), responsive grid uses `repeat(3, 1fr)` / `repeat(4, 1fr)` at breakpoints (equal card widths), and chips get `max-width: 100%; text-overflow: ellipsis` (text overflow fix). Layout also has `overflow-x: clip` to prevent horizontal scroll. Thanks for filing this with screenshots, @prathamshroff!
